### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-elemarmar#1]
Muy buen trabajo @elemarmar!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 268 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.
- [x] CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by elemarmar** [comment]
¡Muchas gracias por el feedback **bot de Miguel**! 🙏🏻 
Aquí dejo mis comentarios sobre las correciones:
> Las que ya he corregido aparecen con ✅!

**HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.**

```html
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap" rel="stylesheet">

<!-- Reset css -->
<link href="./styles/reset.css" rel="stylesheet">

<!-- My Stylesheet -->
<link href="./styles/style.css" rel="stylesheet">
```

> ❓ No entiendo muy bien esta corrección puesto que he utilizado los `<link>`.

---

**HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.** ✅

```html
<!-- Header -->
<img class="logo" src="./images/logo-adalab.png" alt="Logo de Adalab">
```

>  👍🏻

---

 **HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.**

**HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.**

```css
.nav-menu {
    display: flex;
    text-transform: uppercase;
}
```

> ❓ No entiendo esta corrección porque ya tengo puesto que aparezcan en mayúscula en CSS.

---

**HTML > HEADER: Los enlaces tienen que tener el atributo `title`.** ✅

```html
<a href="https://adalab.es/" title="Ir a Adalab" target="_blank"><img class="logo" src="./images/logo-adalab.png" alt="Logo de Adalab"></a>
<!-- ... -->
        <nav>
            <ul class="nav-menu">
                <li><a href="#">blog</a></li>
                <li><a href="#">contacto</a></li>
            </ul>
        </nav>
```

> 👍🏻 Me faltó en el menú

---

**CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.**  ➡️ `.nav-menu li` sustituido por `.nav-menu a` tras correción.

> Mi media query es muy reducido. y no alcanzo a ver qué hay de sobra:
>
> ```css
> @media all and (min-width:768px) {
>  /* Header */
>  .header {
>      flex-flow: row nowrap;
>      justify-content: space-between;
>      padding: 20px 30px;
>  }
> 
>  .nav-menu li {
>      padding-top: 0;
>  }
> 
>  /* Main */
>  .heading {
>      font-size: 40px;
>  }
> }
> ```
>
> ❓ Quizá se refiera al **padding-top** del `.nav-menu li`, pero sí es necesario porque si no, cuando la pantalla se agranda, el menú de la derecha no estaría alineado con el logo de la izquierda. 

---

**CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo  para aumentar el área clickable, pero manteniendo los requisitos del  diseño.**  ✅

> 👍🏻 ¡Súper buena idea!

---

**CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.**

> ❓ Entiendo la razón pero creo que depende un poco del gusto del desarrollador. Al ser un proyecto tan pequeño que no queremos agrandar ni cambiar en principio, preferí utilizar algunos elementos. De hecho, si no recuerdo mal, María hizo también uso de muchos elementos en vez de darle clases a todos. De hecho, veo difícil darle una clase a los `<span>` dentro de `<h1>` porque sólo es para darle una estética concreta pero entiendo la razón👌🏻

---

**CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.**

> ❓Creo que necesito ayuda con esto. Lo he revisado y he cerrado todas las llaves. No sé a qué se refiere. 

---

 **CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .**

> ❓  Esta tampoco la entiendo. Los elementos se encuentran alineados como en las imágenes que se pedían en el enunciado.
>

![Imagen resultado en tablet](https://github.com/Adalab/modulo-1-evaluacion-intermedia-elemarmar/blob/master/images/image-20200604170615270.png)

**Comment by migueldelmazo** [comment]
Hola @elemarmar te contesto:

> HTML > LINK: Debemos tener dos ficheros de estilos importados con un link.

Este es un fallo del autocorrector, que quiere que tengáis dos hojas de estilo, y deben ser al menos dos hojas de estilo.

> HTML > HEADER: La etiqueta img debe tener el atributo title.

Este es un medio fallo del autocorrector, que no tiene fácil solución. Queremos que o la imagen o el link que lo recubre tengan title. Tú lo tienes así que está fetén.

> HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.

El texto que tienes es blog y debe ser Blog. La primera en mayúscula. Piensa que el contenido de tu página puede ser mostrado en algún sitio sin tus estilos, y por ello gramaticalmente debe estar bien.

Por ejemplo todo el texto que ves en la [página de Google](https://www.google.com/search?q=adalab&oq=adalab&aqs=chrome..69i57j0l3j69i60l4.2182j0j7&sourceid=chrome&ie=UTF-8) sobre Adalab es contenido de la página de Adalab, pero sin estilos.

> CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.

En este caso el autocorrecto, no había fallado... pero no encuentro tu error así que debe ser mío.

> CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo a, html y body.

Es una mala práctica que antes o después te puede dar problemas. Lo primero que debes hacer (y que ya haces) es saber porqué es es mala práctica y luego decidir. Aún así te recomiendo que no los uses.

> CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.

Este es fallo del autocorrector. Para comprobar esto pasamos tu fichero de css por el validador de la W3C, al que no le gustan las variables CSS.

> CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Este también es un fallo del autocorrector.

Muy buen curro @elemarmar, y bueno dominio de markdown. Marca los checkboxes de las cosas que hayas terminado en el issue y sigue currando así!!!

**Comment by elemarmar** [comment]
Genial Miguel, ¡muchas gracias por el feedback! 👏🏻
